name: Release Flows

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  publish_next:
    concurrency:
      group: publish_next
      cancel-in-progress: true

    name: Publish @next release to npm

    runs-on: ubuntu-latest

    if: github.repository_owner == 'twiveSDK' && github.event_name == 'release' && github.event.release.prerelease == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build:node

      - name: Publish new @next version
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
            npm publish --access public --tag next

  publish_latest:
    concurrency:
      group: publish_latest
      cancel-in-progress: true

    name: Publish @latest release to npm

    runs-on: ubuntu-latest

    if: github.repository_owner == 'twiveSDK' && github.event_name == 'release' && github.event.release.prerelease == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build:node

      - name: Check if version exists on npm
        run: |
          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VER=$(node -p "require('./package.json').version")
          echo "name=$PKG_NAME" >> $GITHUB_OUTPUT
          echo "ver=$PKG_VER" >> $GITHUB_OUTPUT
          if npm view "$PKG_NAME@$PKG_VER" version >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish new @latest version
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          PKG_NAME="${{ steps.npm_check.outputs.name }}"
          PKG_VER="${{ steps.npm_check.outputs.ver }}"
          EXISTS="${{ steps.npm_check.outputs.exists }}"
      
          if [ "$EXISTS" = "true" ]; then
          npm dist-tag add "$PKG_NAME@$PKG_VER" latest
          else
          npm publish --access public --tag latest
          fi